language: php
sudo: enabled
branches:
  only:
    - master
    - dev
before_install:
  - sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get update
  - sudo apt install -y php7.0 php7.1
notifications:
  slack:
    rooms:
      - shusui:dTl3cqRmVzzrJcvqxHRhUrbu
    on_success: always
    on_failure: always
    template:
          - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
          - "Change view : %{compare_url}"
          - "Build details : %{build_url}"
  email:
    recipients:
      - jere.marchand@gmail.com
    on_success: never # default: change
    on_failure: always # default: always